#include <errno.h>
#include <stdio.h>
#include <string.h>

static void var_name(const char *filename, char *var,  int max_len)
{
  int i, c;
  const char *p;
  
  p = strrchr(filename, '/');
  if (p == NULL)
    p = filename;

  for (i = 0; i+1 < max_len && p[i] != '\0'; i++) {
    c = p[i];
    if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9')) {
        var[i] = c;
    }
    else if (c == '.') {
        var[i] = '\0';
        return;
    }
    else {
      var[i] = '_';
    }
  }

  var[i] = '\0';
}

static int file2c(const char *in_file, const char *out_file)
{
  FILE *in, *out;
  char var[32];
  int c, n;

  in = fopen(in_file, "r");
  if (! in) {
    return -1;
  }
  out = fopen(out_file, "w");
  if (! out) {
    fclose(in);
    return -2;
  }

  var_name(out_file, var, sizeof(var));
  fprintf(out, "/* Auto-generated by f2h, do not edit! */\n");
  fprintf(out, "const static unsigned char %s[] = {", var);
  n = 0;
  while ((c = getc(in)) != EOF) {
    if (n++ % 12 == 0)
      fprintf(out, "\n ");
    fprintf(out, " 0x%02x,", (unsigned int) c);
  }
  fprintf(out, "\n};\n");
  fclose(out);
  fclose(in);
  return 0;
}

int main(int argc, char *argv[])
{
  if (argc != 3) {
    printf("USAGE: %s input_file out_file\n", argv[0]);
    return 1;
  }
  return file2c(argv[1], argv[2]);
}
